#:schema node_modules/wrangler/config-schema.json
name = "cf-worker"
main = "src/index.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "tunnel.xmo.asia/secure", zone_name = "xmo.asia" },
  { pattern = "tunnel.xmo.asia/secure/*", zone_name = "xmo.asia" }
]

[[r2_buckets]]
binding = 'flags'
bucket_name = 'flags'
preview_bucket_name  = 'flags'

[observability]
enabled = true